# # Vim mode
# setw -g mode-keys vi

# # Setup 'v' to begin selection as in Vim
# bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T copy-mode-vi y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"

# # Update default binding of `Enter` to also use copy-pipe
# unbind -T copy-mode-vi Enter
# bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"

# mouse copy support
unbind-key MouseDown3Pane
bind-key -n MouseDown3Pane run " \
  tmux save-buffer - | pbcopy; \
  tmux display-message 'copied!' \
"


# split current window horizontally
bind v split-window -v
# split current window vertically
bind n split-window -h


# pane resizing
bind -r h resize-pane -L 2
bind -r j resize-pane -D 2
bind -r k resize-pane -U 2
bind -r l resize-pane -R 2

# window navigation
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind -r Tab last-window        # move to last active window

# toggle mouse
#bind m run "cut -c3- ~/.tmux.conf | sh -s _toggle_mouse"
#set -g mouse on

#set scrooling limit
set -g history-limit 8000


# Enable mouse support and set mouse mode to 'on'
set-option -g mouse on

# Set the clipboard integration mode to 'tmux'
set-option -g set-clipboard on

# create session
bind C-n new-session

# find session
bind C-f command-prompt -p find-session 'switch-client -t %%'

